npc:
  normal:
    title: '§bОбычная'
    description: 'игроков'
    command: ''
    skin: '307264a1-2c69-11e8-b5ea-1cb72caa35fd'
    pitch: 179
  rating:
    title: '§bРейтинговая'
    description: 'игроков'
    command: ''
    skin: 'bf30a1df-85de-11e8-a6de-1cb72caa35fd'
    pitch: 179
  character:
    title: '§bПерсонаж'
    description: ''
    command: 'menu'
    pitch: 160